services:
  db:
    image: mysql:$c{kea/backend/opts/version}
    restart: unless-stopped
    command: --default-authentication-plugin=caching_sha2_password
    volumes:
      - $c{service/paths/db/data}:/var/lib/mysql
    networks:
      - db0
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=$c{kea/backend/opts/root_password}
      - MYSQL_DATABASE=$c{kea/backend/opts/name}
      - MYSQL_USER=$c{kea/backend/opts/username}
      - MYSQL_PASSWORD=$c{kea/backend/opts/password}
  kea:
    image: $c{image/repository/url}/$c{image/repository/name}:$c{image/repository/tag}
    restart: unless-stopped
    depends_on: [ db ]
    cap_add:
      - NET_ADMIN
      - NET_RAW
    privileged: true
    volumes:
      - $c{service/paths/kha/root}:$c{service/paths/kha/root}
      - $c{service/paths/kea/config}:/etc/kea
      - $c{service/paths/kea/lib}:/var/lib/kea
      - $c{service/paths/kea/log}:/var/log/kea
      - $c{service/paths/kea/run}:/var/run/kea
      - $c{service/paths/kea/tmp}:/var/tmp/kea
      - $c{service/paths/supervisor/log}:/var/log/supervisor
    networks:
      db0:
      mgmt0:
        ipv4_address: $c{service/networking/mgmt/ipv4/address}
      service0:
        ipv4_address: $c{service/networking/service/ipv4/address}
    ports:
      - $c{service/ports/tcp/http}:$c{service/ports/tcp/http}
    env_file:
      - .env
networks:
  db0:
    name: db0
    driver: bridge
  mgmt0:
    name: mgmt0
    driver: ipvlan
    driver_opts:
      ipvlan_mode: l2
      parent: $c{service/networking/mgmt/interface}
    ipam:
      driver: default
      config:
        - subnet: $c{service/networking/mgmt/ipv4/address}/$c{service/networking/mgmt/ipv4/netmask}
          gateway: $c{service/networking/mgmt/ipv4/gateway}
  service0:
    name: service0
    driver: ipvlan
    driver_opts:
      ipvlan_mode: l2
      parent: $c{service/networking/service/interface}
    ipam:
      driver: default
      config:
        - subnet: $c{service/networking/service/ipv4/address}/$c{service/networking/service/ipv4/netmask}
          gateway: $c{service/networking/service/ipv4/gateway}